dist: trusty
sudo: false
language: node_js
node_js:
  - 6.9.1
addons:
  sonarqube: true
  branches:
    - master
    - features/travis
env:
  global:
  - secure: I9ovxVH6r2px+vNX7F42ZCoo+1nDb4yWA6tj4KvuAdUZau4VF8+Z1kDkTfZgoigxCNOr9Snlgh1H3SONRgRuNas5Df+mZqXQKQNb8td3r5TBsSgsu+zhBlIehnb6Tz/xKARdmhhlp7s67wrdEZo8Y6fjfJVjs8eedRo/5w0PfDU+W3c6ZoB1DZwYIyjLChoXZrbB8ELTxiJdFkcW4MfCW29SJmn1HgzknT0NpMMmTC5VZ7ei6MYc1BGvdnuNUXDFh1/eeVQX7O/v5+nF3t4ERkz6sEhIAiNFOyoDiskDY6JTZijnVmTd2r1WQiKY3/S0Xygkh0XqoAC5L0VKxS3a9dbEle8U++yHZp+oOkDR6nJM1rs6f5F69sqWfg6DCdlIfGM8PqjYj0+3lTi1bcuqUmRerc3bq3nsZMN5JTRENP9WUAfZDNVt2SjXUko6KnrghMfYNlzkicAXWGFnB8xXOJ0EkyoztUKT8EbUkMGT0S0mcHjW6iIXdJ0U/0lvuYlwGsKSfSD0i2jhD3u45Pie4NGV5EpMbHb4TOqvv5Rrdd2QJoLnQP0XnS21ZYqHrUIUBpdeYEIjWRum2BVboAtTkQCIxAYCbbbRBVp5HqmAzknCZWQcK/Sup7mvWYcFenGMmG7jbNmAExYa0JJ8JU80jLZA3Ao/1jgIAYKyKrN9QXw=
cache:
  - anaf.app/node_modules 
  - $HOME/.npm
  - $HOME/.nvm
install:
  - npm install -g typings 
  - npm install -g cordova
  - npm install -g ionic
before_script:
  - cd ./anaf.app
  - npm install
  - cd src
  - typings install
  - cd ..
  - mkdir platforms
  - mkdir plugins
  - mkdir www
script:
  - ionic state restore
  - npm run build
  - cd ..
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN